with credit_q1 as (
    select
        loan_id,
        date,
        customer_age,
        total_paid,
        total_due_today,
        coalesce(balance, 0) as balance,
        days_past_due,
        closing_balance,
        advance,
        balance_due_to_date,
        arrears,
        balance_due_status,
        payment,
        expected_payment,
        first_payment,
        first_expected_payment,
        account_status_l1,
        account_status_l2,
        return_date,
        sale_date,
        credit_check_done,
        payment_amount,
        adjustment_amount,
        prepayment_amount,
        deposit,
        weekly_rate,
        credit_expiry,
        next_invoice_date,
        coalesce(balance, 0) as discount,
        overpayment_amount,
        max_payment_date,
        initial_pay,
        total_paid_with_adjustments_15d,
        NULL as LOAN_TERM,
        NULL as customer_id,
        'Q1' as quarter
    from {{ ref('creditdata-q1') }}
),

credit_q2 as (
    select
        loan_id,
        date,
        customer_age,
        total_paid,
        total_due_today,
        coalesce(balance, 0) as balance,
        days_past_due,
        closing_balance,
        advance,
        balance_due_to_date,
        arrears,
        balance_due_status,
        payment,
        expected_payment,
        first_payment,
        first_expected_payment,
        account_status_l1,
        account_status_l2,
        return_date,
        sale_date,
        credit_check_done,
        payment_amount,
        adjustment_amount,
        prepayment_amount,
        deposit,
        weekly_rate,
        credit_expiry,
        next_invoice_date,
        coalesce(balance, 0) as discount,
        overpayment_amount,
        max_payment_date,
        initial_pay,
        total_paid_with_adjustments_15d,
        NULL as LOAN_TERM,
        NULL as customer_id,
        'Q2' as quarter
    from {{ ref('creditdata-q2') }}
),

credit_q3 as (
    select
        loan_id,
        date,
        customer_age,
        total_paid,
        total_due_today,
        coalesce(balance, 0) as balance,
        days_past_due,
        closing_balance,
        advance,
        balance_due_to_date,
        arrears,
        balance_due_status,
        payment,
        expected_payment,
        first_payment,
        first_expected_payment,
        account_status_l1,
        account_status_l2,
        return_date,
        sale_date,
        credit_check_done,
        payment_amount,
        adjustment_amount,
        prepayment_amount,
        deposit,
        weekly_rate,
        credit_expiry,
        next_invoice_date,
        NULL as discount,
        NULL as overpayment_amount,
        NULL as max_payment_date,
        NULL as initial_pay,
        NULL as total_paid_with_adjustments_15d,
        NULL as LOAN_TERM,
        NULL as customer_id,
        'Q3' as quarter
    from {{ ref('creditdata-q3') }}
),

credit_q4 as (
    select
        loan_id,
        date,
        customer_age,
        total_paid,
        total_due_today,
        coalesce(balance, 0) as balance,
        days_past_due,
        closing_balance,
        advance,
        balance_due_to_date,
        arrears,
        balance_due_status,
        payment,
        expected_payment,
        first_payment,
        first_expected_payment,
        account_status_l1,
        account_status_l2,
        return_date,
        sale_date,
        credit_check_done,
        payment_amount,
        adjustment_amount,
        prepayment_amount,
        deposit,
        weekly_rate,
        credit_expiry,
        next_invoice_date,
        NULL as discount,
        NULL as overpayment_amount,
        NULL as max_payment_date,
        NULL as initial_pay,
        NULL as total_paid_with_adjustments_15d,
        NULL as LOAN_TERM,
        NULL as customer_id,
        'Q4' as quarter
    from {{ ref('creditdata-q4') }}
),

credit_q5 as (
    select
        loan_id,
        date,
        customer_age,
        total_paid,
        total_due_today,
        coalesce(balance, 0) as balance,
        days_past_due,
        closing_balance,
        advance,
        balance_due_to_date,
        arrears,
        balance_due_status,
        payment,
        expected_payment,
        first_payment,
        first_expected_payment,
        account_status_l1,
        account_status_l2,
        return_date,
        sale_date,
        credit_check_done,
        payment_amount,
        adjustment_amount,
        prepayment_amount,
        deposit,
        weekly_rate,
        credit_expiry,
        next_invoice_date,
        NULL as discount,
        NULL as overpayment_amount,
        NULL as max_payment_date,
        NULL as initial_pay,
        NULL as total_paid_with_adjustments_15d,
        NULL as LOAN_TERM,
        NULL as customer_id,
        'Q5' as quarter
    from {{ ref('creditdata-q5') }}
),

joined_loans as (
    select * from credit_q1
    union all
    select * from credit_q2
    union all
    select * from credit_q3
    union all
    select * from credit_q4
    union all
    select * from credit_q5
)

select * from joined_loans

